### ISSUE TITLE
failed build .so

### ISSUE THREAD

**Issue by TimHuDi** [renatoGarcia/opencv-swig#11]
Hi renato:
     I follow the readme to try, when I excute g++ to produce .so file , build failed.My log is attached, and the I use ubuntu14.04,python2.7.6,swig2.0.11, I use the same .hpp and .i as in your readme.
[log.txt](https://github.com/renatoGarcia/opencv-swig/files/2158135/log.txt)

**Comment by renatoGarcia** [comment]
Hi TimHuDi,

It's because you are using SWIG 2.x instead of SWIG 3.x.
With SWIG2 the [construction](https://github.com/renatoGarcia/opencv-swig/blob/master/lib/opencv/matx.i#L162):

```C++
Matx(std::vector<value_type> arg)
{
    return Factory< $parentclassname >::construct(arg);
}
```

will expand to C++ functions like:

```C++
SWIGINTERN cv::Matx< uint8_t,2,1 > *new_cv_Matx_Sl_uint8_t_Sc_2_Sc_1_Sg___SWIG_6(std::vector< cv::Matx< unsigned char,2,1 >::value_type,std::allocator< cv::Matx< uint8_t,2,1 >::value_type > > arg){
        return Factory< cv::Matx<(uint8_t,2,1)> >::construct(arg);
    }
```
while with SWIG3:

```C++
SWIGINTERN cv::Matx< uint8_t,2,1 > *new_cv_Matx_Sl_uint8_t_Sc_2_Sc_1_Sg___SWIG_6(std::vector< cv::Matx< unsigned char,2,1 >::value_type,std::allocator< cv::Matx< uint8_t,2,1 >::value_type > > arg){
        return Factory< cv::Matx< uint8_t,2,1 > >::construct(arg);
    }
```

Note the parenthesis on `cv::Matx<(uint8_t,2,1)>`.

A solution to that it is update the SWIG on your system to a 3.x version.
