### ISSUE TITLE
How to use cv::Mat <--> numpy array

### ISSUE THREAD

**Issue by huckw** [renatoGarcia/opencv-swig#17]
Let's say I have the following function...

`inline
float getMean( cv::Mat img)
{
    return cv::mean(img)[0];
}`

In python I am expecting to do this...

```
import my_lib
import cv2

I=cv2.imread('someimage.png')
themean = my_lib.getMean(I)
```

But I a TypeError argument 2 of type  'cv::Mat'

What is the correct way to do this?

**Comment by renatoGarcia** [comment]
This problem is because the OpenCV `cv2` python module uses a numpy `ndarray` to handle images. So, when you do:

    I=cv2.imread('someimage.png')

the type of `I` variable is `ndarray`. To your example works, you need to convert the `I` variable to a `cv::Mat` wrapped python type, as in:

    my_lib.Mat.from_array(I)

Look at the issue #16 to a similar situation.

**Comment by huckw** [comment]
Bingo!!  Thank you for the quick reply and the great library!

**Comment by Yousef-Hesham** [comment]
Hello, How did you manage to import Mat into python? I cant do that

**Comment by renatoGarcia** [comment]
Hello @Yousef-Hesham.
You will need to import the module you just compiled, and use `Mat` name inside it. Just like:
```
import my_lib
my_lib.Mat
```
Do you have managed follow the [dello world](https://github.com/renatoGarcia/opencv-swig#hello-world) example?
