### ISSUE TITLE
OpenCV 4 Support?

### ISSUE THREAD

**Issue by spencerbug** [renatoGarcia/opencv-swig#22]
Is there any plans to support OpenCV 4?

**Comment by mauvilsa** [comment]
@renatoGarcia it would be great to support opencv 4 to not let this project die. There has been stable opencv 4 releases since more than a year ago. Also the official version of opencv in Ubuntu 20.04 will be version 4.1 and surely other distributions will follow.

If currently you don't have the time to do this, maybe give some guidance so that maybe someone else contributes with a pull request?

**Comment by renatoGarcia** [comment]
Hi @spencerbug and @mauvilsa,

I have updated the lib and fixed the bug that was preventing it to work with OpenCV 4. It's highly unlikely that I will add new types and functionalities any time soon, by I intend keep it working with new OpenCV releases, and prevent it to bit rot.

If anyone wish add new code however, I will be happy to help with directions.

**Comment by mauvilsa** [comment]
@renatoGarcia I have tried out the new version with opencv 4.2 and some code that uses opencv-swig and all seems to work well. Thank you!
